<a id='section_id2'></a>

# Numpy

In [2]:
import numpy as np

## <font color=blue>创建数组</font>

numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)

In [19]:
np.array([1, 2, 3])

array([1, 2, 3])

In [20]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [21]:
np.array([(1, 2, 3), (4, 5, 6)])

array([[1, 2, 3],
       [4, 5, 6]])

<font color=red>numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)</font>

In [15]:
x = np.arange(6)
x = x.reshape((2, 3))
x

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])

In [2]:
np.arange(1,5,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

np.random.choice(a, size=None, replace=True, p=None)

In [3]:
np.random.choice(5,3)

array([0, 4, 3])

np.concatenate 数组拼接

In [8]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[11,21,31],[7,8,9]])
np.concatenate((a,b),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 21, 31],
       [ 7,  8,  9]])

## <font color=blue>矩阵运算</font>

linalg.norm(x, ord=None, axis=None, keepdims=False)
- 求向量或矩阵的范数
- 对于向量：对向量而言，二范数就是数组元素平方和开根号，所以 ord = None 和 ord = 2 一样
- 对于矩阵：对矩阵而言，二范数是转置矩阵乘矩阵（$x^Tx$）的最大特征值开根号，不是矩阵所有元素平方和开根号。因此 ord = None是求所有元素平方和开根号，ord = 2是求二范数

In [22]:
a = np.arange(9)-4
a = a.reshape((3,3))
a

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [25]:
np.linalg.norm(a) #结果是根号60

7.745966692414834

In [ ]:
distances = np.array([min([np.linalg.norm(point - center) ** 2 for center in self.cluster_centers_]) for point in X])

## <font color=blue>生成随机数</font>

自1.17版本之后，Numpy提供了一个新的用于生成随机数的类叫Generator（以前的是RandomState，老的函数，比如np.random.random，依然可以运行但将不再更新），建议用新的Generator来生成随机数。

### I. Legacy Random Generation(RandomState)

In [32]:
np.random.seed(42) #设置种子，这个在新的generator里面就没用了，新的generator是在生成的时候指定seed

In [34]:
np.random.random((3, 3))

array([[0.18340451, 0.30424224, 0.52475643],
       [0.43194502, 0.29122914, 0.61185289],
       [0.13949386, 0.29214465, 0.36636184]])

In [3]:
np.random.rand(4)

array([0.05056468, 0.35370102, 0.13314964, 0.772     ])

### II. Random Generator

random.Generator.random(size=None, dtype=np.float64, out=None)
- Return random floats in the half-open interval [0.0, 1.0).
- size: int or tuple of ints, optional. Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.

In [51]:
rng = np.random.default_rng(seed=42)  # Create a Generator.
rng.random(size=10)  # Generate 10 samples.

array([0.77395605, 0.43887844, 0.85859792, 0.69736803, 0.09417735,
       0.97562235, 0.7611397 , 0.78606431, 0.12811363, 0.45038594])

In [72]:
rng = np.random.default_rng(seed=42)  # Create a Generator.
rng.random((3, 3)) #为啥每次的随机数都不一样？一定要在同一个cell里面生成generator


array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235],
       [0.7611397 , 0.78606431, 0.12811363]])

## <font color=blue>Sorting, searching, and counting</font>

#### <font color=red> numpy.argmin(a, axis=None, out=None, *, keepdims=\<no value>) </font>
- Returns the indices of the minimum values along an axis. 给出axis方向最小值的索引

In [9]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
np.argmin(a)

0

In [11]:
np.argmin(a, axis=0)

array([0, 0, 0], dtype=int64)

In [12]:
np.argmin(a, axis=1)

array([0, 0], dtype=int64)

In [ ]:
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0]])

#### numpy.where(condition, [x, y, ]/)
- 如果condition == True, 则返回x中的元素，反之返回y中的元素。返回值是一个array
- 如果只传入condition参数，当condition ==True时，返回的是每个符合condition条件元素的索引,返回的是以元组的形式

In [17]:
a = np.arange(10)
np.where(a < 5, a, 10*a) 

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [18]:
np.where(a < 5) 

(array([0, 1, 2, 3, 4], dtype=int64),)

## <font color=blue>统计</font>

numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)

In [14]:
a = np.array([[1, 2], [3, 4]])
print(np.mean(a))
print(np.mean(a,axis=0))
print(np.mean(a, axis=1))

2.5
[2. 3.]
[1.5 3.5]


## 数据类型转换

In [ ]:
import pandas as pd

pd.Series.to_numpy()
pd.DataFrame.to_numpy()